Header header
float64 Sail                         # '<Root>/Sail'
float64 Rudder                       # '<Root>/Rudder'
float64 speed_angle_d                # '<Root>/speed_angle_d'
float64 speed_angle                  # '<Root>/speed_angle'
float64 wind_speed                   # '<Root>/wind_speed'
float64 wind_angle_ground            # '<Root>/wind_angle_ground'
float64 leg                          # '<Root>/leg'
float64 los_heading                  # '<Root>/los_heading'