Header header
float64 rudder                       # '<Root>/rudder'
float64 sail                         # '<Root>/sail'
float64 wind_angle_ground            # '<Root>/wind_angle_ground'
float64 wind_speed                   # '<Root>/wind_speed'
float64 speed_angle                  # '<Root>/speed_angle'
float64 leg                          # '<Root>/leg'
float64 los_heading                  # '<Root>/los_heading'
float64 speed_angle_d                # '<Root>/speed_angle_d'#
float64 drive_force
float64 sail_ground_d