Header header
float64 Kd                           # Variable: Kd
float64 Ki                           # Variable: Ki
float64 Kp                           # Variable: Kp
float64 R                            # Variable: R
float64 jibing_time                  # Variable: jibing_time
float64 leg                          # Variable: leg
float64 max_loose_time               # Variable: max_loose_time
float64 max_roll_allowed             # Variable: max_roll_allowed
float64 pos_history_len              # Variable: pos_history_len
float64 run_period                   # Variable: run_period
float64 ship_speed_history_len       # Variable: ship_speed_history_len
float64 tacking_discount_decrease_windspeed # Variable: tacking_discount_decrease_windspeed
float64 tacking_force_discount       # Variable: tacking_force_discount
float64 tacking_time                 # Variable: tacking_time
float64 upwind_R_expand_ratio        # Variable: upwind_R_expand_ratio
float64 wind_mean_time               # Variable: wind_mean_time
float64 Airmar_X_Value               # Expression: -0.61
float64 Airmar_Z_Value               # Expression: 0.8
                                     #  Referenced by: '<Root>/Airmar_Z'