bool all_result
float32 checkAHRS_param
float32 checkWTST_param
float32 checkArduino_param
float32 checkCamera_param
float32 checkRadar_param
float32 checkDynamixel_param
float32 checkDisk_param
int16 checkAHRS_result
int16 checkWTST_result
int16 checkArduino_result
int16 checkCamera_result
int16 checkRadar_result
int16 checkDynamixel_result
int16 checkDisk_result
---
bool ack