Header header
float64 sail_ground_d                # // '<Root>/sail_ground_d'
float64 max_drive_force              # // '<Root>/max_drive_force'
float64 rudder                       # // '<Root>/rudder'
float64 sail                         # // '<Root>/sail'
float64 ship_speed                   # // '<Root>/ship_speed'
float64 speed_angle_d                # // '<Root>/speed_angle_d'
float64 wind_angle_ground            # // '<Root>/wind_angle_ground'
float64 wind_speed                   # // '<Root>/wind_speed'
float64 leg                          # // '<Root>/leg'
float64 obstacle_judge